// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneWebShop.Business;

namespace PhoneWebShop.Business.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220112134732_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneWebShop.Domain.Objects.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("PhoneWebShop.Domain.Objects.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VAT")
                        .HasColumnType("float");

                    b.Property<double>("VATPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "An oldie but goldie.",
                            Stock = 1,
                            Type = "Iphone 6",
                            VAT = 0.0,
                            VATPrice = 150.0
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Description = "Better than Iphone 6 but worse than the Samsung Galaxy S7.",
                            Stock = 69,
                            Type = "Iphone 7",
                            VAT = 0.0,
                            VATPrice = 299.0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Description = "Better than Iphone 7 but worse than the Samsung Galaxy S8.",
                            Stock = 32,
                            Type = "Galaxy S7",
                            VAT = 0.0,
                            VATPrice = 369.0
                        });
                });

            modelBuilder.Entity("PhoneWebShop.Domain.Objects.Phone", b =>
                {
                    b.HasOne("PhoneWebShop.Domain.Objects.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
